In [81]:
import os
from dotenv import load_dotenv
from bs4 import BeautifulSoup
import requests
import pandas as pd
import requests

In [82]:
load_dotenv()

def get_soup(url):
    page = requests.get(url,headers = {"User-Agent":"Mozilla/5.0","origin":"https://www.transfermarkt.co.uk"})
    soup = BeautifulSoup(page.content, 'html.parser')
    return soup

In [83]:
df = pd.read_csv('../CSVs/player_transfers.csv')
df

,Unnamed: 0,season,date,left,joined,mv,fee,name
0,0,20/21,"Oct 5, 2020",Atlético Madrid,Arsenal,£36.00m,£45.00m,Thomas Partey
1,1,15/16,"Jul 1, 2015",Atl. Madrid B,Atlético Madrid,£3.60m,-,Thomas Partey
2,2,14/15,"Jun 30, 2015",UD Almería,Atl. Madrid B,£2.25m,End of loan,Thomas Partey
3,3,14/15,"Jul 27, 2014",Atl. Madrid B,UD Almería,£900Th.,loan transfer,Thomas Partey
4,4,13/14,"Jun 30, 2014",RCD Mallorca,Atl. Madrid B,£900Th.,End of loan,Thomas Partey
...,...,...,...,...,...,...,...,...
10905,6,16/17,"Jun 30, 2017",SM Caen,G. Bordeaux,£2.25m,End of loan,Frédéric Guilbert
10906,7,16/17,"Oct 24, 2016",G. Bordeaux,SM Caen,£1.80m,loan transfer,Frédéric Guilbert
10907,8,15/16,"Jul 1, 2015",G. Bordeaux B,G. Bordeaux,-,-,Frédéric Guilbert
10908,9,14/15,"Jul 1, 2014",AS Cherbourg,G. Bordeaux B,-,free transfer,Frédéric Guilbert
10909,10,13/14,"Jul 1, 2013",SM Caen B,AS Cherbourg,-,free transfer,Frédéric Guilbert

In [84]:
df["date"] = pd.to_datetime(df["date"])
df

,Unnamed: 0,season,date,left,joined,mv,fee,name
0,0,20/21,2020-10-05,Atlético Madrid,Arsenal,£36.00m,£45.00m,Thomas Partey
1,1,15/16,2015-07-01,Atl. Madrid B,Atlético Madrid,£3.60m,-,Thomas Partey
2,2,14/15,2015-06-30,UD Almería,Atl. Madrid B,£2.25m,End of loan,Thomas Partey
3,3,14/15,2014-07-27,Atl. Madrid B,UD Almería,£900Th.,loan transfer,Thomas Partey
4,4,13/14,2014-06-30,RCD Mallorca,Atl. Madrid B,£900Th.,End of loan,Thomas Partey
...,...,...,...,...,...,...,...,...
10905,6,16/17,2017-06-30,SM Caen,G. Bordeaux,£2.25m,End of loan,Frédéric Guilbert
10906,7,16/17,2016-10-24,G. Bordeaux,SM Caen,£1.80m,loan transfer,Frédéric Guilbert
10907,8,15/16,2015-07-01,G. Bordeaux B,G. Bordeaux,-,-,Frédéric Guilbert
10908,9,14/15,2014-07-01,AS Cherbourg,G. Bordeaux B,-,free transfer,Frédéric Guilbert
10909,10,13/14,2013-07-01,SM Caen B,AS Cherbourg,-,free transfer,Frédéric Guilbert

In [85]:
df["mv"].head(10)

0    £36.00m
1     £3.60m
2     £2.25m
3    £900Th.
4    £900Th.
5          -
6          -
7    £18.00m
8    £540Th.
9    £540Th.
Name: mv, dtype: object

In [86]:
import re

def convert_mv(mv):
    if 'm' in str(mv):
        converted_mv = re.sub('[^0-9.]', '', str(mv))
        return float(converted_mv) * 1000000
    elif 'Th.' in str(mv):
        converted_mv = re.sub('[^0-9.]', '', str(mv))
        return float(converted_mv) * 1000
    elif mv == '-' or mv =='?':
        return None
    else:
        return mv

In [87]:
df["mv"] = df["mv"].apply(lambda x: convert_mv(x))
df

,Unnamed: 0,season,date,left,joined,mv,fee,name
0,0,20/21,2020-10-05,Atlético Madrid,Arsenal,36000000.0,£45.00m,Thomas Partey
1,1,15/16,2015-07-01,Atl. Madrid B,Atlético Madrid,3600000.0,-,Thomas Partey
2,2,14/15,2015-06-30,UD Almería,Atl. Madrid B,2250000.0,End of loan,Thomas Partey
3,3,14/15,2014-07-27,Atl. Madrid B,UD Almería,900000.0,loan transfer,Thomas Partey
4,4,13/14,2014-06-30,RCD Mallorca,Atl. Madrid B,900000.0,End of loan,Thomas Partey
...,...,...,...,...,...,...,...,...
10905,6,16/17,2017-06-30,SM Caen,G. Bordeaux,2250000.0,End of loan,Frédéric Guilbert
10906,7,16/17,2016-10-24,G. Bordeaux,SM Caen,1800000.0,loan transfer,Frédéric Guilbert
10907,8,15/16,2015-07-01,G. Bordeaux B,G. Bordeaux,NaN,-,Frédéric Guilbert
10908,9,14/15,2014-07-01,AS Cherbourg,G. Bordeaux B,NaN,free transfer,Frédéric Guilbert
10909,10,13/14,2013-07-01,SM Caen B,AS Cherbourg,NaN,free transfer,Frédéric Guilbert

In [88]:
df["fee_details"] = df["fee"]
df["fee"] = df["fee"].apply(lambda x: 0 if x == 'End of loan' or x == 'free transfer' or x == 'loan transfer' else convert_mv(x))
df

,Unnamed: 0,season,date,left,joined,mv,fee,name,fee_details
0,0,20/21,2020-10-05,Atlético Madrid,Arsenal,36000000.0,45000000.0,Thomas Partey,£45.00m
1,1,15/16,2015-07-01,Atl. Madrid B,Atlético Madrid,3600000.0,None,Thomas Partey,-
2,2,14/15,2015-06-30,UD Almería,Atl. Madrid B,2250000.0,0,Thomas Partey,End of loan
3,3,14/15,2014-07-27,Atl. Madrid B,UD Almería,900000.0,0,Thomas Partey,loan transfer
4,4,13/14,2014-06-30,RCD Mallorca,Atl. Madrid B,900000.0,0,Thomas Partey,End of loan
...,...,...,...,...,...,...,...,...,...
10905,6,16/17,2017-06-30,SM Caen,G. Bordeaux,2250000.0,0,Frédéric Guilbert,End of loan
10906,7,16/17,2016-10-24,G. Bordeaux,SM Caen,1800000.0,0,Frédéric Guilbert,loan transfer
10907,8,15/16,2015-07-01,G. Bordeaux B,G. Bordeaux,NaN,None,Frédéric Guilbert,-
10908,9,14/15,2014-07-01,AS Cherbourg,G. Bordeaux B,NaN,0,Frédéric Guilbert,free transfer
10909,10,13/14,2013-07-01,SM Caen B,AS Cherbourg,NaN,0,Frédéric Guilbert,free transfer

In [89]:
df.loc[(df["fee_details"] != 'End of loan') & (df["fee_details"] != 'free transfer') & (df["fee_details"] != 'loan transfer'),'fee_details'] = None
df

,Unnamed: 0,season,date,left,joined,mv,fee,name,fee_details
0,0,20/21,2020-10-05,Atlético Madrid,Arsenal,36000000.0,45000000.0,Thomas Partey,None
1,1,15/16,2015-07-01,Atl. Madrid B,Atlético Madrid,3600000.0,None,Thomas Partey,None
2,2,14/15,2015-06-30,UD Almería,Atl. Madrid B,2250000.0,0,Thomas Partey,End of loan
3,3,14/15,2014-07-27,Atl. Madrid B,UD Almería,900000.0,0,Thomas Partey,loan transfer
4,4,13/14,2014-06-30,RCD Mallorca,Atl. Madrid B,900000.0,0,Thomas Partey,End of loan
...,...,...,...,...,...,...,...,...,...
10905,6,16/17,2017-06-30,SM Caen,G. Bordeaux,2250000.0,0,Frédéric Guilbert,End of loan
10906,7,16/17,2016-10-24,G. Bordeaux,SM Caen,1800000.0,0,Frédéric Guilbert,loan transfer
10907,8,15/16,2015-07-01,G. Bordeaux B,G. Bordeaux,NaN,None,Frédéric Guilbert,None
10908,9,14/15,2014-07-01,AS Cherbourg,G. Bordeaux B,NaN,0,Frédéric Guilbert,free transfer
10909,10,13/14,2013-07-01,SM Caen B,AS Cherbourg,NaN,0,Frédéric Guilbert,free transfer

In [90]:
df[["first_name","surname","other_names"]] = df["name"].str.lower().str.split(' ',2,expand=True)
df["transfer_row"] = df["Unnamed: 0"]

,season,date,left,joined,mv,fee,fee_details,first_name,surname,other_names,transfer_row
0,20/21,2020-10-05,Atlético Madrid,Arsenal,36000000.0,45000000.0,None,thomas,partey,None,0
1,15/16,2015-07-01,Atl. Madrid B,Atlético Madrid,3600000.0,None,None,thomas,partey,None,1
2,14/15,2015-06-30,UD Almería,Atl. Madrid B,2250000.0,0,End of loan,thomas,partey,None,2
3,14/15,2014-07-27,Atl. Madrid B,UD Almería,900000.0,0,loan transfer,thomas,partey,None,3
4,13/14,2014-06-30,RCD Mallorca,Atl. Madrid B,900000.0,0,End of loan,thomas,partey,None,4
...,...,...,...,...,...,...,...,...,...,...,...
10905,16/17,2017-06-30,SM Caen,G. Bordeaux,2250000.0,0,End of loan,frédéric,guilbert,None,6
10906,16/17,2016-10-24,G. Bordeaux,SM Caen,1800000.0,0,loan transfer,frédéric,guilbert,None,7
10907,15/16,2015-07-01,G. Bordeaux B,G. Bordeaux,NaN,None,None,frédéric,guilbert,None,8
10908,14/15,2014-07-01,AS Cherbourg,G. Bordeaux B,NaN,0,free transfer,frédéric,guilbert,None,9
10909,13/14,2013-07-01,SM Caen B,AS Cherbourg,NaN,0,free transfer,frédéric,guilbert,None,10

In [91]:
df["date_from"] = df['date']
df['date_to'] = df['date'].shift(1)
df

,Unnamed: 0,season,date,left,joined,mv,fee,name,fee_details,first_name,surname,other_names,transfer_row,date_from,date_to
0,0,20/21,2020-10-05,Atlético Madrid,Arsenal,36000000.0,45000000.0,Thomas Partey,None,thomas,partey,None,0,2020-10-05,NaT
1,1,15/16,2015-07-01,Atl. Madrid B,Atlético Madrid,3600000.0,None,Thomas Partey,None,thomas,partey,None,1,2015-07-01,2020-10-05
2,2,14/15,2015-06-30,UD Almería,Atl. Madrid B,2250000.0,0,Thomas Partey,End of loan,thomas,partey,None,2,2015-06-30,2015-07-01
3,3,14/15,2014-07-27,Atl. Madrid B,UD Almería,900000.0,0,Thomas Partey,loan transfer,thomas,partey,None,3,2014-07-27,2015-06-30
4,4,13/14,2014-06-30,RCD Mallorca,Atl. Madrid B,900000.0,0,Thomas Partey,End of loan,thomas,partey,None,4,2014-06-30,2014-07-27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,6,16/17,2017-06-30,SM Caen,G. Bordeaux,2250000.0,0,Frédéric Guilbert,End of loan,frédéric,guilbert,None,6,2017-06-30,2017-07-28
10906,7,16/17,2016-10-24,G. Bordeaux,SM Caen,1800000.0,0,Frédéric Guilbert,loan transfer,frédéric,guilbert,None,7,2016-10-24,2017-06-30
10907,8,15/16,2015-07-01,G. Bordeaux B,G. Bordeaux,NaN,None,Frédéric Guilbert,None,frédéric,guilbert,None,8,2015-07-01,2016-10-24
10908,9,14/15,2014-07-01,AS Cherbourg,G. Bordeaux B,NaN,0,Frédéric Guilbert,free transfer,frédéric,guilbert,None,9,2014-07-01,2015-07-01
10909,10,13/14,2013-07-01,SM Caen B,AS Cherbourg,NaN,0,Frédéric Guilbert,free transfer,frédéric,guilbert,None,10,2013-07-01,2014-07-01

In [92]:
df.loc[df["transfer_row"] == 0,"date_to"] = None
df

,Unnamed: 0,season,date,left,joined,mv,fee,name,fee_details,first_name,surname,other_names,transfer_row,date_from,date_to
0,0,20/21,2020-10-05,Atlético Madrid,Arsenal,36000000.0,45000000.0,Thomas Partey,None,thomas,partey,None,0,2020-10-05,NaT
1,1,15/16,2015-07-01,Atl. Madrid B,Atlético Madrid,3600000.0,None,Thomas Partey,None,thomas,partey,None,1,2015-07-01,2020-10-05
2,2,14/15,2015-06-30,UD Almería,Atl. Madrid B,2250000.0,0,Thomas Partey,End of loan,thomas,partey,None,2,2015-06-30,2015-07-01
3,3,14/15,2014-07-27,Atl. Madrid B,UD Almería,900000.0,0,Thomas Partey,loan transfer,thomas,partey,None,3,2014-07-27,2015-06-30
4,4,13/14,2014-06-30,RCD Mallorca,Atl. Madrid B,900000.0,0,Thomas Partey,End of loan,thomas,partey,None,4,2014-06-30,2014-07-27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,6,16/17,2017-06-30,SM Caen,G. Bordeaux,2250000.0,0,Frédéric Guilbert,End of loan,frédéric,guilbert,None,6,2017-06-30,2017-07-28
10906,7,16/17,2016-10-24,G. Bordeaux,SM Caen,1800000.0,0,Frédéric Guilbert,loan transfer,frédéric,guilbert,None,7,2016-10-24,2017-06-30
10907,8,15/16,2015-07-01,G. Bordeaux B,G. Bordeaux,NaN,None,Frédéric Guilbert,None,frédéric,guilbert,None,8,2015-07-01,2016-10-24
10908,9,14/15,2014-07-01,AS Cherbourg,G. Bordeaux B,NaN,0,Frédéric Guilbert,free transfer,frédéric,guilbert,None,9,2014-07-01,2015-07-01
10909,10,13/14,2013-07-01,SM Caen B,AS Cherbourg,NaN,0,Frédéric Guilbert,free transfer,frédéric,guilbert,None,10,2013-07-01,2014-07-01

In [95]:
df = df[["season","date_from","date_to","left","joined","mv","fee","fee_details","first_name","surname","other_names"]].drop_duplicates()
df

,season,date_from,date_to,left,joined,mv,fee,fee_details,first_name,surname,other_names
0,20/21,2020-10-05,NaT,Atlético Madrid,Arsenal,36000000.0,45000000.0,None,thomas,partey,None
1,15/16,2015-07-01,2020-10-05,Atl. Madrid B,Atlético Madrid,3600000.0,None,None,thomas,partey,None
2,14/15,2015-06-30,2015-07-01,UD Almería,Atl. Madrid B,2250000.0,0,End of loan,thomas,partey,None
3,14/15,2014-07-27,2015-06-30,Atl. Madrid B,UD Almería,900000.0,0,loan transfer,thomas,partey,None
4,13/14,2014-06-30,2014-07-27,RCD Mallorca,Atl. Madrid B,900000.0,0,End of loan,thomas,partey,None
...,...,...,...,...,...,...,...,...,...,...,...
10905,16/17,2017-06-30,2017-07-28,SM Caen,G. Bordeaux,2250000.0,0,End of loan,frédéric,guilbert,None
10906,16/17,2016-10-24,2017-06-30,G. Bordeaux,SM Caen,1800000.0,0,loan transfer,frédéric,guilbert,None
10907,15/16,2015-07-01,2016-10-24,G. Bordeaux B,G. Bordeaux,NaN,None,None,frédéric,guilbert,None
10908,14/15,2014-07-01,2015-07-01,AS Cherbourg,G. Bordeaux B,NaN,0,free transfer,frédéric,guilbert,None
10909,13/14,2013-07-01,2014-07-01,SM Caen B,AS Cherbourg,NaN,0,free transfer,frédéric,guilbert,None

In [96]:
df.to_csv('../CSVs/player_transfers_cleaned.csv')